class RegistrationAccount {
    registerHeaderText = '.ant-space-item'
    basicInformationForm ='#basic'

    listTextBase = '.title.text-base.font-normal'
    uploadFileBtn = '.ant-upload button'
    enterAbbreviationParticipating1 ='#basic_participatingUnitChineseName'
    enterAbbreviationParticipating2 ='#basic_participatingUnitEnglishName'
    enterLegalEntity ='#basic_legalEntity'
    enterCorporateName ='#basic_corporateNameAbbr'
    enterCorporateCode ='#basic_corporateCode'
    enterManagingDirector1 ='#basic_chineseName'
    enterManagingDirector2 ='#basic_englishName'
    enterAddress1 = '#basic_addressEnglishFormInput1'
    enterAddress2 = '#basic_addressEnglishFormInput2'

    enterContactDivision ='#basic_contactDivision'
    enterDesignation = '#basic_designation'
    enterContactPerson1 = '#basic_contactPersonChineseName'
    enterContactPerson2 ='#basic_contactPersonEnglishName'
    enterPhone = '#basic_contactPersonPhone'
    enterFax = '#basic_contactPersonFax'
    enterMailingAddress1 = '#basic_mailingAddressInput1'
    enterMailingAddress2 = '#basic_mailingAddressInput2'
    enterEmail ='#basic_contactPersonEmail'
    enterCopyEmail1 ='#basic_copyEmailDefault'
    enterCopyEmail2 = '#basic_copyEmail_0_email'

    radioEntityNationalityTaiwan = '.ant-radio-input[value ="TAIWAN"]'
    radioEntityNationalityForeign = '.ant-radio-input[value ="FOREIGN"]'
    radioEntityNationalityForeignOptions = '#basic_corNationality'
    radioWhetherPublishReportYes = '.ant-radio-input[value="true"]'
    radioWhetherPublishReportNo = '.ant-radio-input[value="false"]'
    yearIncorporated = '#basic_yearIncorporated'
    listingSituation_ListedPublicly = '.ant-radio-input[value="listedPublicly"]'
    listingSituation_OTC = '.ant-radio-input[value="OTC"]'
    listingSituation_NotListed = '.ant-radio-input[value="notListed"]'
    enterStock = '#basic_stock'
    organizationType = '#basic_orgType'
    sizeOfOperation = '#basic_sizeOfOperation'
    industry = '#basic_industry'
    GRICategory = '#basic_gRICategory'
    capitalization1 = '#basic_capitalizationFormInput1'
    capitalization2 = '#basic_capitalizationFormInput2'
    chairmanOfTheBoard1 = '#basic_chairmanOfTheBoardFormChineseName'
    chairmanOfTheBoar2 = '#basic_chairmanOfTheBoardFormEnglishName'
    generalManagerName1 = '#basic_generalManagerNameFormEnglishName'
    generalManagerName2 ='#basic_generalManagerNameFormEnglishName'
    employeeDistributionMale = '#basic_employeeDistributionFormMale'
    employeeDistributionFemale = '#basic_employeeDistributionFormFemale'
    fullTimeEmployees = '#basic_fullTimeEmployees'
    partTimeEmployees = '#basic_partTimeEmployees'
    employeesWithDisabilities ='#basic_employeesDisabilities'
    organizationOfficialWebsite = '#basic_orgOfficialWebsite'
    corporateCSRWebsite1 = '#basic_corporateCSRWebsite'
    taiwanCorporateWebsite = '#basic_taiwanCorporateWebsiteEnglish'
    corporateCSRWebsite2 = '#basic_corporateWebsiteEnglish'
    companyDescriptionChina = '#basic_companyDescriptionChinese'
    companyDescriptionEnglish = '#basic_companyDescriptionEnglish'

    revenueGovernmentBudgetDroplist = '#basic_revenues_y2019_revenueOrGovernmentBudgetFormInput1'
    revenueGovernmentBudgetRevenues= '#basic_revenues_y2032_revenueOrGovernmentBudgetFormInput2'
    globalRevenueDroplist = '#basic_revenues_y2032_globalRevenueFormInput1'
    globalRevenueGlobal ='#basic_revenues_y2032_globalRevenueFormInput2'
    enterpriseIncomeTaxDroplist = '#basic_revenues_y2032_enterpriseIncomeTaxFormInput1'
    enterpriseIncomeTax = '#basic_revenues_y2032_enterpriseIncomeTaxFormInput2'
    taiwanMarketValueDroplist = '#basic_revenues_y2032_taiwanMarketValueFormInput1'
    taiwanMarketValueMarket ='#basic_revenues_y2032_taiwanMarketValueFormInput2'
    EPSValueDroplist = '#basic_revenues_y2032_epsValueFormInput1'
    EPSValueEPS = '#basic_revenues_y2032_epsValueFormInput2'
    foreignOwnershipRatioPercent = '#basic_revenues_y2032_foreignOwnershipRatio'
    annualCSRReportTitlesChinese ='#basic_revenues_y2032_annualCSRReportTitleChinese'
    annualCSRReportTitlesEnglish = '#basic_revenues_y2032_annualCSRReportTitleEnglish'
    supplementaryExplanationRevenue = '#basic_supplementary'
    currentYearFirstSeasonEPSDroplist = '#basic_currentYearFirstSeasonEPSFormInput1'
    currentYearFirstSeasonEPSFirst ='#basic_currentYearFirstSeasonEPSFormInput2'
    currentYearSecondSeasonEPSDroplist = '#basic_currentYearSecondSeasonEPSFormInput1'
    currentYearSecondSeasonEPSSeason = '#basic_currentYearSecondSeasonEPSFormInput2'
    iAgreeCheckbox = '.ant-checkbox-input[type="checkbox"]'
    completeBtn = 'button[type="submit"]'
}
const registrationAccount = new RegistrationAccount();
export  default registrationAccount;