class RegistrationAccount {
    signUpBtn = 'button[type="button"]'
    registerHeader = '.ant-space-item'
    basicInformationForm = '#basic'
    groupRegistrationAcctName = '.ant-collapse-header-text'
    arrowViewIcon = '.anticon.anticon-right.ant-collapse-arrow'
    NTDcurrencyOptions = '.ant-select-item.ant-select-item-option.ant-select-item-option-active[title="NTD"]'
    USDcurrencyOptions = '.ant-select-item.ant-select-item-option[title="USD"]'

    listTextBase = '.title.text-base.font-normal'
    uploadFileBtn = '.ant-upload button'
    businessRegistrationCertificate = '#basic_businessRegistrationCertificate'
    enterAbbreviationParticipating1 = '#basic_participatingUnitChineseName'
    enterAbbreviationParticipating2 = '#basic_participatingUnitEnglishName'
    enterLegalEntity = '#basic_legalEntity'
    enterCorporateName = '#basic_corporateNameAbbr'
    enterCorporateCode = '#basic_corporateCode'
    enterManagingDirector1 = '#basic_chineseName'
    enterManagingDirector2 = '#basic_englishName'
    enterAddressPostCode1 = '#basic_addressFormInput1'
    enterAddress1 = '#basic_addressFormInput2'
    enterAddressPostCode2 = '#basic_addressEnglishFormInput1'
    enterAddress2 = '#basic_addressEnglishFormInput2'

    enterContactDivision = '#basic_contactDivision'
    enterDesignation = '#basic_designation'
    enterContactPerson1 = '#basic_contactPersonChineseName'
    enterContactPerson2 = '#basic_contactPersonEnglishName'
    enterPhoneCountry = '#basic_phoneCountryCode'
    enterPhoneNumber ='#basic_phoneNumber'
    enterPhoneExtension = '#basic_phoneExtension'
    enterFax = '#basic_contactPersonFax'
    enterMailingAddress1 = '#basic_mailingAddressInput1'
    enterMailingAddress2 = '#basic_mailingAddressInput2'
    enterEmail = '#basic_contactPersonEmail'
    enterCopyEmail1 = '#basic_copyEmailDefault>input'
    enterCopyEmail2 = '#basic_copyEmail_0_email>input'

    orgImageFileInput = '#basic_orgImageFile'
    orgImageFileInputAIType = '#basic_orgImageFileAI'
    radioEntityNationalityTaiwan = '.ant-radio-input[value ="TAIWAN"]'
    radioEntityNationalityForeign = '.ant-radio-input[value ="FOREIGN"]'
    radioEntityNationalityForeignOptions = '#basic_corNationality'
    radioEntityNationalityForeignOptionsValue = '.ant-select-item-option-content'
    radioWhetherPublishReportYes = '.ant-radio-input[value="true"]'
    radioWhetherPublishReportNo = '.ant-radio-input[value="false"]'
    yearIncorporated = '#basic_yearIncorporated'
    headquartersEstablishmentYear='#basic_headquartersEstablishmentYear'
    listingSituation_ListedPublicly = '.ant-radio-input[value="listedPublicly"]'
    listingSituation_OTC = '.ant-radio-input[value="OTC"]'
    listingSituation_NotListed = '.ant-radio-input[value="notListed"]'
    enterStock = '#basic_stock'
    organizationType = '#basic_orgType'
    organizationType_Companies = '.ant-select-item.ant-select-item-option[title="Companies"]'
    organizationType_Universities = '.ant-select-item.ant-select-item-option[title="Universities"]'
    organizationType_GovernmentAgencies = '.ant-select-item.ant-select-item-option[title="Government Agencies"]'
    organizationType_Hospitals = '.ant-select-item.ant-select-item-option[title="Hospitals"]'
    organizationType_NGOs = '.ant-select-item.ant-select-item-option[title="NGOs"]'
    organizationType_Others = '.ant-select-item.ant-select-item-option[title="Others"]'
    // sizeOfOperation = '#basic_sizeOfOperation'
    // SizeOfOperation_LargeEnterprise = '.ant-select-item.ant-select-item-option[title="Large Enterprise"]'
    // sizeOfOperation_SmallAndMedium = '.ant-select-item.ant-select-item-option[title="Small and Medium Enterprise"]'
    // sizeOfOperation_MultinationalEnterprise = '.ant-select-item.ant-select-item-option[title="Multinational Enterprise"]'
    mainMethodsOfOperating ='.ant-radio-input[value="TRADING"]'
    industry = '#basic_industry'
    industry_Agriculture = '.ant-select-item.ant-select-item-option[title="Agriculture, forestry, fishery, animal husbandry"]'
    industry_MiningAndEarth = '.ant-select-item.ant-select-item-option[title="Mining and earth and stone extraction industry"]'
    industry_TraditionalManufacturing = '.ant-select-item.ant-select-item-option[title="Traditional manufacturing"]'
    industry_ElectronicComponentManufacturing = '.ant-select-item.ant-select-item-option[title="Electronic component manufacturing"]'
    industry_Computer = '.ant-select-item.ant-select-item-option[title="Computer, electronic products and optical products manufacturing industry"]'
    industry_ElectricityAndGas = '.ant-select-item.ant-select-item-option[title="Electricity and gas supply industry"]'
    industry_WaterSupply = '.ant-select-item.ant-select-item-option[title="Water supply and pollution control industry"]'
    industry_ConstructionIndustry = '.ant-select-item.ant-select-item-option[title="Construction industry"]'
    industry_WholesaleAndRetail = '.ant-select-item.ant-select-item-option[title="Wholesale and retail trade"]'
    industry_TransportationAndWarehouse = '.ant-select-item.ant-select-item-option[title="Transportation and warehouse industry"]'
    GRICategory = '#basic_gRICategory'
    GRICategory_Agriculture = '.ant-select-item.ant-select-item-option[title="Agriculture"]'
    GRICategory_Automotive = '.ant-select-item.ant-select-item-option[title="Automotive"]'
    GRICategory_Aviation = '.ant-select-item.ant-select-item-option[title="Aviation"]'
    GRICategory_Chemicals = '.ant-select-item.ant-select-item-option[title="Chemicals"]'
    GRICategory_CommercialServices = '.ant-select-item.ant-select-item-option[title="Commercial Services"]'
    GRICategory_Computers = '.ant-select-item.ant-select-item-option[title="Computers"]'
    GRICategory_Conglomerates = '.ant-select-item.ant-select-item-option[title="Conglomerates"]'
    GRICategory_Construction = '.ant-select-item.ant-select-item-option[title="Construction"]'
    GRICategory_ConstructionMaterials = '.ant-select-item.ant-select-item-option[title="Construction Materials"]'
    GRICategory_ConsumerDurables = '.ant-select-item.ant-select-item-option[title="Consumer Durables"]'
    capitalization1 = '#basic_capitalizationFormInput1'
    capitalization2 = '#basic_capitalizationFormInput2'
    chairmanOfTheBoard1 = '#basic_chairmanOfTheBoardFormChineseName'
    chairmanOfTheBoar2 = '#basic_chairmanOfTheBoardFormEnglishName'
    generalManagerName1 = '#basic_generalManagerNameFormChineseName'
    generalManagerName2 = '#basic_generalManagerNameFormEnglishName'
    employeeDistributionMale = '#basic_employeeDistributionFormMale'
    employeeDistributionFemale = '#basic_employeeDistributionFormFemale'
    fullTimeEmployees = '#basic_fullTimeEmployees'
    partTimeEmployees = '#basic_partTimeEmployees'
    employeesWithDisabilities = '#basic_employeesDisabilities'
    organizationOfficialWebsite = '#basic_orgOfficialWebsite'
    corporateCSRWebsite1 = '#basic_corporateCSRWebsite'
    taiwanCorporateWebsite = '#basic_taiwanCorporateWebsiteEnglish'
    corporateCSRWebsite2 = '#basic_corporateWebsiteEnglish'
    companyDescriptionChina = '#basic_companyDescriptionChinese'
    companyDescriptionEnglish = '#basic_companyDescriptionEnglish'

    yearBtn = '.flex.flex-row.items-center.justify-start.year-container > div'
    revenueGovernmentBudgetDroplist1 = '#basic_revenues_y2019_revenueOrGovernmentBudgetFormInput1'
    revenueGovernmentBudgetRevenues1 = '#basic_revenues_y2019_revenueOrGovernmentBudgetFormInput2'
    globalRevenueDroplist1 = '#basic_revenues_y2019_globalRevenueFormInput1'
    globalRevenueGlobal1 = '#basic_revenues_y2019_globalRevenueFormInput2'
    enterpriseIncomeTaxDroplist1 = '#basic_revenues_y2019_enterpriseIncomeTaxFormInput1'
    enterpriseIncomeTax1 = '#basic_revenues_y2019_enterpriseIncomeTaxFormInput2'
    taiwanMarketValueDroplist1 = '#basic_revenues_y2019_taiwanMarketValueFormInput1'
    taiwanMarketValueMarket1 = '#basic_revenues_y2019_taiwanMarketValueFormInput2'
    EPSValueDroplist1 = '#basic_revenues_y2019_epsValueFormInput1'
    EPSValueEPS1 = '#basic_revenues_y2019_epsValueFormInput2'
    foreignOwnershipRatioPercent1 = '#basic_revenues_y2019_foreignOwnershipRatio'
    annualCSRReportTitlesChinese1 = '#basic_revenues_y2019_annualCSRReportTitleChinese'
    annualCSRReportTitlesEnglish1 = '#basic_revenues_y2019_annualCSRReportTitleEnglish'
    revenueGovernmentBudgetDroplist2 = '#basic_revenues_y2020_revenueOrGovernmentBudgetFormInput1'
    revenueGovernmentBudgetRevenues2 = '#basic_revenues_y2020_revenueOrGovernmentBudgetFormInput2'
    globalRevenueDroplist2 = '#basic_revenues_y2020_globalRevenueFormInput1'
    globalRevenueGlobal2 = '#basic_revenues_y2020_globalRevenueFormInput2'
    enterpriseIncomeTaxDroplist2 = '#basic_revenues_y2020_enterpriseIncomeTaxFormInput1'
    enterpriseIncomeTax2 = '#basic_revenues_y2020_enterpriseIncomeTaxFormInput2'
    taiwanMarketValueDroplist2 = '#basic_revenues_y2020_taiwanMarketValueFormInput1'
    taiwanMarketValueMarket2 = '#basic_revenues_y2020_taiwanMarketValueFormInput2'
    EPSValueDroplist2 = '#basic_revenues_y2020_epsValueFormInput1'
    EPSValueEPS2 = '#basic_revenues_y2020_epsValueFormInput2'
    foreignOwnershipRatioPercent2 = '#basic_revenues_y2020_foreignOwnershipRatio'
    annualCSRReportTitlesChinese2 = '#basic_revenues_y2020_annualCSRReportTitleChinese'
    annualCSRReportTitlesEnglish2 = '#basic_revenues_y2020_annualCSRReportTitleEnglish'
    revenueGovernmentBudgetDroplist3 = '#basic_revenues_y2021_revenueOrGovernmentBudgetFormInput1'
    revenueGovernmentBudgetRevenues3 = '#basic_revenues_y2021_revenueOrGovernmentBudgetFormInput2'
    globalRevenueDroplist3 = '#basic_revenues_y2021_globalRevenueFormInput1'
    globalRevenueGlobal3 = '#basic_revenues_y2021_globalRevenueFormInput2'
    enterpriseIncomeTaxDroplist3 = '#basic_revenues_y2021_enterpriseIncomeTaxFormInput1'
    enterpriseIncomeTax3 = '#basic_revenues_y2021_enterpriseIncomeTaxFormInput2'
    taiwanMarketValueDroplist3 = '#basic_revenues_y2021_taiwanMarketValueFormInput1'
    taiwanMarketValueMarket3 = '#basic_revenues_y2021_taiwanMarketValueFormInput2'
    EPSValueDroplist3 = '#basic_revenues_y2021_epsValueFormInput1'
    EPSValueEPS3 = '#basic_revenues_y2021_epsValueFormInput2'
    foreignOwnershipRatioPercent3 = '#basic_revenues_y2021_foreignOwnershipRatio'
    annualCSRReportTitlesChinese3 = '#basic_revenues_y2021_annualCSRReportTitleChinese'
    annualCSRReportTitlesEnglish3 = '#basic_revenues_y2021_annualCSRReportTitleEnglish'
    revenueGovernmentBudgetDroplist4 = '#basic_revenues_y2022_revenueOrGovernmentBudgetFormInput1'
    revenueGovernmentBudgetRevenues4 = '#basic_revenues_y2022_revenueOrGovernmentBudgetFormInput2'
    globalRevenueDroplist4 = '#basic_revenues_y2022_globalRevenueFormInput1'
    globalRevenueGlobal4 = '#basic_revenues_y2022_globalRevenueFormInput2'
    enterpriseIncomeTaxDroplist4 = '#basic_revenues_y2022_enterpriseIncomeTaxFormInput1'
    enterpriseIncomeTax4 = '#basic_revenues_y2022_enterpriseIncomeTaxFormInput2'
    taiwanMarketValueDroplist4 = '#basic_revenues_y2022_taiwanMarketValueFormInput1'
    taiwanMarketValueMarket4 = '#basic_revenues_y2022_taiwanMarketValueFormInput2'
    EPSValueDroplist4 = '#basic_revenues_y2022_epsValueFormInput1'
    EPSValueEPS4 = '#basic_revenues_y2022_epsValueFormInput2'
    foreignOwnershipRatioPercent4 = '#basic_revenues_y2022_foreignOwnershipRatio'
    annualCSRReportTitlesChinese4 = '#basic_revenues_y2022_annualCSRReportTitleChinese'
    annualCSRReportTitlesEnglish4 = '#basic_revenues_y2022_annualCSRReportTitleEnglish'
    revenueGovernmentBudgetDroplist5 = '#basic_revenues_y2023_revenueOrGovernmentBudgetFormInput1'
    revenueGovernmentBudgetRevenues5 = '#basic_revenues_y2023_revenueOrGovernmentBudgetFormInput2'
    globalRevenueDroplist5 = '#basic_revenues_y2023_globalRevenueFormInput1'
    globalRevenueGlobal5 = '#basic_revenues_y2023_globalRevenueFormInput2'
    enterpriseIncomeTaxDroplist5 = '#basic_revenues_y2023_enterpriseIncomeTaxFormInput1'
    enterpriseIncomeTax5 = '#basic_revenues_y2023_enterpriseIncomeTaxFormInput2'
    taiwanMarketValueDroplist5 = '#basic_revenues_y2023_taiwanMarketValueFormInput1'
    taiwanMarketValueMarket5 = '#basic_revenues_y2023_taiwanMarketValueFormInput2'
    EPSValueDroplist5 = '#basic_revenues_y2023_epsValueFormInput1'
    EPSValueEPS5 = '#basic_revenues_y2023_epsValueFormInput2'
    foreignOwnershipRatioPercent5 = '#basic_revenues_y2023_foreignOwnershipRatio'
    annualCSRReportTitlesChinese5 = '#basic_revenues_y2023_annualCSRReportTitleChinese'
    annualCSRReportTitlesEnglish5 = '#basic_revenues_y2023_annualCSRReportTitleEnglish'


    supplementaryExplanationRevenue = '#basic_supplementary'
    currentYearFirstSeasonEPSDroplist = '#basic_currentYearFirstSeasonEPSFormInput1'
    currentYearFirstSeasonEPSFirst = '#basic_currentYearFirstSeasonEPSFormInput2'
    currentYearSecondSeasonEPSDroplist = '#basic_currentYearSecondSeasonEPSFormInput1'
    currentYearSecondSeasonEPSSeason = '#basic_currentYearSecondSeasonEPSFormInput2'
    affiliatedEntityCheckBox ='#basic_affiliated_entity'
    affiliatedEntityName = '#basic_affiliated_entity_name'
    affiliatedEntityEditor = '#basic_affiliated_entity_editor'
    iAgreeCheckbox = '.ant-checkbox-input[type="checkbox"]'
    completeBtn = 'button[type="submit"]'
    messageSuccess ='.ant-notification-notice-message'

    registerHeaderText = 'Member Registration'
    basicInformation = 'Basic Information'
    registrationCertificate = 'Registration certificate'
    abbreviationOfTheParticipatingUnit = 'Abbreviation of the participating unit (used for award promotion, mainly within 6 characters)'
    legalEntity = 'Legal Entity'
    theFullEnglishTitle = 'The Full English Title Of The Participating Unit'
    corporateCode = 'Corporate Code'
    managingDirector = 'Managing Director'
    address = 'Address'
    addressEnglish = 'Address (English)'
    contactPersonGroup = 'Contact Person'
    contactDivision = 'Contact Division'
    designation = 'Designation'
    contactPerson = 'Contact Person'
    phone = 'Phone'
    mailingAddress = 'Mailing Address'
    email = 'Email'
    copyEmail = 'Copy Email'
    unitInformation = 'Unit Information'
    organizationLogo = 'Organization’s “LOGO Image File”'
    entityNationality = 'Entity Nationality'
    yearIncorporat = 'Year Incorporated'
    listingSituationInTaiwan = 'Listing Situation in Taiwan'
    stock = 'Stock'
    organizationTyp = 'Organization Type'
    sizeOfOpera = 'Size of Operation'
    industr = 'Industry'
    GRICate = 'GRI Category'
    textMessageRegisSuccess ='Submit Success'
}

const registrationAccount = new RegistrationAccount();
export default registrationAccount;