class RegistrationInformation{
    registrationInformationTab = '.col-span-2'
    question1_RegulatoryCompliance = '//*[@id="basic_compliance-performance"]//input[@class="ant-radio-input"]'
    question1_YesInput = '#basic_compliance-performance-2-opt-longtext'
    question2_CSRAwards = '//*[@id="basic_certification-status"]//input[@class="ant-checkbox-input"]'
    question2_CSRAwardsOtherInput ='#basic_certification-status-other'
    question3_ManagementTools = '//*[@id="basic_management-tools"]//input[@class ="ant-checkbox-input"]'
    question3_ManagementToolsOtherInput='#basic_management-tools-other'
    question4_ChiefDepartment ='//*[@id="basic_chief-department-of-csr"]//input[@class ="ant-radio-input"]'
    question4_ChiefDepartmentOtherInput ='#basic_chief-department-of-csr-other'
    question5_ProfessionalStaffInput ='#basic_professional-staff'
    question6_NumberOfEmployeesInput ='#basic_certificated-employee'
    question7_ProjectOrProgram ='#basic_project-program-staffing'
    question8_HaveYouEstablished= '#basic_csr-strategy-formulation-team'
    question9_TitleOfTop= '#basic_top-executive'
    question10_WhichAreYour = '//*[@id="basic_long-term-cooperating-institutions"]//input[@class="ant-checkbox-input"]'
    question10_WhichAreYourOtherInput = '#basic_long-term-cooperating-institutions-other'
    question11_WhatWereThe = '//*[@id="basic_csr-critical-motivations"]//input[@class="ant-checkbox-input"]'
    question11_WhatWereTheOtherInput = '#basic_csr-critical-motivations-other'
    question12_GivenYourExisting = '//*[@id="basic_reportage-benefits"]//input[@class="ant-checkbox-input"]'
    question12_GivenYourExistingOtherInput = '#basic_reportage-benefits-other'
    question13_ChallengesAndDifficulties = '//*[@id="basic_csr-challenges-difficulties"]//input[@class="ant-checkbox-input"]'
    question13_ChallengesAndDifficultiesOtherInput = '#basic_csr-challenges-difficulties-other'
    question14_FollowingFactors = '//*[@id="basic_influential-factors"]//input[@class="ant-checkbox-input"]'
    question14_FollowingFactorsOtherInput ='#basic_influential-factors-other'
    question15_KeyOpportunities = '//*[@id="basic_emerging-megaforces-opportunities"]//input[@class="ant-checkbox-input"]'
    question15_KeyOpportunitiesOtherInput = '#basic_emerging-megaforces-opportunities-other'
    question16_TheSource = '//*[@id="basic_largest-risks"]//input[@class="ant-checkbox-input"]'
    question16_TheSourceOtherInput ='#basic_largest-risks-other'
    question17_MostImportantCSR ='#basic_csr-promotion-level'
    question18_FirmColleagues ='#basic_colleagues-value-csr'
    question19_ReasonsForYourCompany = '//*[@id="basic_Reasons-participate-tcsa"]//input[@class="ant-checkbox-input"]'
    question19_ReasonsForYourCompanyOtherInput ='#basic_Reasons-participate-tcsa-other'
    question20_DegreeOfCorrelation ='#basic_degree-of-correlation'
    question21_YourFirmBoard ='//*[@id="basic_board-of-directors"]//input[@class="ant-checkbox-input"]'
    question22_AnnualBudget ='#basic_birth-allowance-annual-budget'
    question23_CompanyAnnualBudget ='#basic_childcare-subsidies-annual-budget'
    question24_DescribeTheCommunity ='#basic_community-service-leave-policy'
    question25_CompanyUnderstanding = '//*[@id="basic_understanding-sdgs"]//input[@class="ant-checkbox-input"]'
    question25_CompanyUnderstandingOtherInput = '#basic_understanding-sdgs-other'
    question26_MainChallenges = '//*[@id="basic_sdgs-challenges-difficulties"]//input[@class="ant-radio-input"]'
    question26_MainChallengesOtherInput = '#basic_sdgs-challenges-difficulties-other'
    question27_OrganizationKey = '//*[@id="basic_organization-key-partners"]//input[@class="ant-checkbox-input"]'
    question27_OrganizationKeyOtherInput = '#basic_organization-key-partners-other'
    question28_CurrentCorporate = '//*[@id="basic_reflected-sdgs"]//input[@class="ant-checkbox-input"]'
    question28_CurrentCorporateOtherInput = '#basic_reflected-sdgs-other'
    question29_ItemsApply = '//*[@id="basic_organization-sustainability-report"]//input[@class="ant-checkbox-input"]'
    question29_ItemsApplyOtherInput = '#basic_organization-sustainability-report-other'
    checkbox1 = '//*[@id="basic_authorization-statement"]//input[@class="ant-checkbox-input"]'
    checkbox2 = '//*[@id="basic_revocation-statement"]//input[@class="ant-checkbox-input"]'
    saveAsDraftBtn ='button[type="button"]'
    submitBtn = 'button[type="submit"]'
    OKConfirmBtn ='button[type="button"]'


}
const registrationInformation = new RegistrationInformation();
export default registrationInformation;